### ISSUE TITLE
[Suggestion]Make energy readings rounded

### ISSUE THREAD

**Issue by Xikaro** [GregTechCEu/GregTech#1062]
**Is your feature request related to a problem? Please describe.**
I'd like to suggest, in top tooltips, rounded values so they don't go out of bounds, like kEU and the like

**Additional context**
![Screenshot_45](https://user-images.githubusercontent.com/55663835/176981876-c143ac3c-caa2-4a9a-8352-5ed079399992.png)

**Comment by Exaxxion** [comment]
I could certainly see usefulness in truncating values longer than say six digits to three meaningful digits plus an SI prefix.

The number in the image is easier to understand as `33.5 MEU` rather than `33554432 EU`, and it would ensure that even exceptionally large numbers render nicely like the MAX battery's `9.22 EEU` (as opposed to cramming `9223372036854775807 EU` into a tooltip).

**Comment by lordclips** [comment]
No idea how ToP handles inputs at all, but maybe a setting (default on for truncation) and if you crouch it shows the whole value instead of the truncated one?

Might be useful, even if getting the full reading becomes exponentially less reasonable to care about at scale

**Comment by Xikaro** [comment]
in gregicprobe, the number is truncated, which is very convenient
