### ISSUE TITLE
Crash on startup w. NuclearCraft: Overhauled

### ISSUE THREAD

**Issue by Shazuli** [GregTechCEu/GregTech#1169]
### GregTech CEu Version

2.4.1-beta

### Environment

Startup

### Side Crashed

Client

### New Worlds

Unsure

### Steps to Reproduce

1. Install GTCEu with [NuclearCraft: Overhauled](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled).
2. Wait ...
3. ...
4. .. crash.

### Crash Report

[crash-2022-08-31_17.17.34-client.txt](https://github.com/GregTechCEu/GregTech/files/9462799/crash-2022-08-31_17.17.34-client.txt)

### Additional Information

This was tested with just GTCEu, CodeChicken Lib (3.2.3.357) and [NuclearCraft](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled) (2o.6.2-1.12.2).

**Comment by ALongStringOfNumbers** [comment]
This is due to the reworked recipe system in GTCEu with the latest release. There are currently PRs to both NC and NCO to fix up the integration between them and GTCEu, although the issue being fixed will have to wait until they are merged and released.

As a workaround, you can disable the GTCE/GTCEu integration from NC in the NC config file.

**Comment by Antineutrino-4444** [comment]
> 

How do I disable the integration in the config file? Any possible idea for which line it is on?
