### ISSUE TITLE
Sterilized Cleanroom Hatch

### ISSUE THREAD

**Issue by adamcirillo** [GregTechCEu/GregTech#1267]
### GregTech CEu Version

2.3.4

### Your Solution

Would be great to have a Sterilized Cleanroom Hatch that works like automatic filtration maintenance for the multiblock machines

**Comment by Syrcan** [comment]
There are two relevant things to mention:
- It is intentional by design to not have a Sterilized Maintenance Hatch. Cleanroom is an essential part of gameplay. Making it irrelevant in the lategame would be almost identical to disabling it, which is an option you have as player in `gregtech.cfg`.
- That being said, I think having the Sterilized Maintenance Hatch exist **but** disabled by default could be a good compromise, for modpack devs.

**Comment by adamcirillo** [comment]
The automatic filtration maintenance hatch recipe needs a UV Hull so it is pretty much endgame at point anyway I figured this would be the same. I understand the point that it is by design then or would it cause some problems then with GCYS?

**Comment by Syrcan** [comment]
The point is to allow your regular cleanroom recipes to be run in your multiblocks that have a filtration hatch.
But higher tier (wetware related) cleanroom recipes will still require the cleanroom.
