### ISSUE TITLE
Basic assembler does not craft Diode using ULV Red Alloy Recipe

### ISSUE THREAD

**Issue by Azeranth** [GregTechCEu/GregTech#1365]
### GregTech CEu Version

v2.4.5-beta

### Modpack Used

Nomifactory GTCEu Port

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Expected to produce 4 Diode in Basic Assembler using 1 Steel Bolt and 2 Copper Wire 1x with Red Alloy.
Expected to produce 2 Diode in Basic Assembling Machine using 2 Steel Bolt and 2 Copper Wire 1x with programmed Circuit configuration 1

### Actual Behavior

Recipe is not accepted by machine

### Steps to Reproduce

Power Basic assembling machine and add either combination of ingredients

### Additional Information

Error is possibly a result of NEI not showing proper requirements to craft, such as Voltage requirements being incorrect.

**Comment by ALongStringOfNumbers** [comment]
First off, instead of Diode I assume you mean Vacuum Tube, as that is what the recipes you are describing make.

In addition, in the Vacuum Tube recipes there is another item called `Glass Tube`, which can be a bit hard to see, but is required for all Vacuum Tube assembler recipes. It is the same component that is present in the regular crafting table recipe for the Vacuum Tube.
