### ISSUE TITLE
Tools lose their oredicts after deal a damage

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/GregTech#1452]
### GregTech CEu Version

2.5.0

### Modpack Used

TFG:NH R4.1.12

### Addons Installed

GM v1.1.6

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

Tool must not lose oredict

### Actual Behavior

Lose their oredicts

### Steps to Reproduce

1) Take any tool, for example knife
2) Do something..
3) If you have spent durability, then the oredicts are also gone, congratulations.

### Additional Information

https://user-images.githubusercontent.com/52341158/214824525-8e0e6b49-81ba-4430-98be-a02c4725ff3b.mp4

**Comment by Xikaro** [comment]
error persisted
![image](https://user-images.githubusercontent.com/55663835/221955889-3d6453b4-d94d-43dc-a702-1efe96d98243.png)
![image](https://user-images.githubusercontent.com/55663835/221955912-cee93323-cef5-433b-8d92-3d46e4c82a11.png)

**Comment by msgerbs** [comment]
I'm also seeing this on 2.5.2-beta.

**Comment by TechLord22** [comment]
On the current master branch, with commit hash 96e838b, I am unable to reproduce this. Can you provide further reproduction steps?

**Comment by SpeeeDCraft** [comment]
they lose the oredict that Crafttweaker or Groovyscript(not tested) assigns to them

before using the tool:
![image](https://user-images.githubusercontent.com/52341158/222654984-27955de1-da7d-40d7-96ee-e10ed3ec83f4.png)

after using(where knife oredict)
![image](https://user-images.githubusercontent.com/52341158/222655177-238a835f-12bf-4687-8835-98ad83c23329.png)

**Comment by IntegerLimit** [comment]
Can confirm.

**Comment by msgerbs** [comment]
Personally, I am playing on TFGNH-Extended 4.2.2 if that helps. https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/releases/tag/R4.2.2

**Comment by TechLord22** [comment]
After further investigation we found the reason why, and it is something you can fix within your scripts.

Currently adding a GT tool to an oredict with CT, like this, will have the problem: 
```zs
<ore:mySword>.add(<gregtech:sword>)
```

The root cause of this is a bug in the Forge OreDictionary, which uses the item's damage/durability to retrieve the ore dictionaries it possesses. It in reality should be using the item's metadata. In order to work around this bug, we create a special case where a tool is using the wildcard metadata upon oredict registration, so it behaves correctly.

In order to utilize our workaround, you will need to adjust your scripts to look like the following:
```zs
<ore:mySword>.add(<gregtech:sword:*>)
// or
<ore:mySword>.add(<gregtech:sword:32767>)
```

Both methods are equivalent. `*` or `32767` is the item meta wildcard value, which is intended for use when you want to accept any meta value for your itemstack.

If you add GT tools to ore dictionaries with the meta wildcard value, you should no longer experience this bug.

**Comment by SpeeeDCraft** [comment]
Nice, it's really works, thank you!
