### ISSUE TITLE
Naquadah line dupes fluorine

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1616]
### GregTech CEu Version

2.5.4

### Modpack Used

GT Comunity pack 1.6.1

### Addons Installed

N/A

### Environment

N/A

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Expected: Nq line recycles all fluorine 100%, no loss but also no gain

That is  not the case, however, there was an oversight that dupes fluorine, i think it "costs" sulfuric acid not sure didnt bother to check cus its literally free.

It goes as follows. Im ot going to include antimony trifluoride in the calculations because that one is a closed loop and works as intended. gets recycled 100% no problems there.

So the cost per recipe of 6 Nq duts is 4 buckets of HF; 4 HF is 4 buckets of fluorine; we get 3HF=3F from the titanium trifluoride, ok so far so good, we then get the remaining 1 bucket from the acidid Nq solution (0.5 eache) ( I group them as one cus they are basically the same and work the same way). OK so we get all 4 buckets back great, but wait there's more, if we process the Nq waste we get more Nq solution->Acidic Nq solution-> More fluorine + Waste....... It goes like this in a geometric progression or wtv giving less each time but basically this free fluorine gets generated every time Nq waste is processed it is not accounted for in the base recipes and therefore the whole process is very much fluorine positive. I know from experience of leaving it running on a server and the fluorine tank filling up more and more as time passes.

### Actual Behavior

recipe loop oversight, also distillation recipe is dumb make it consistent so i can make 1 DT only any% speedrun, it would also make more sense

### Steps to Reproduce

check recipes

**Comment by Sanduhr32** [comment]
Yes this is a geometric series, but seems to be intentional no?
Naquadah isn't a real element (yet).
If it can be enriched into 2 different isotopes and yield other elements in minor quantities then let it be it.
Naquadria is 2 neutrons lighter than Naquadah
Enriched Naquadah is 2 neutrons heavier than Naquadah
(that preserves 2 naquadah out of the 6 so far)
you seem to forget that trinium, titanium, gallium, barium and flourine are way lighter in their masses than the other 4 naquadah you inserted making it reasonable to have a flourine gain for the decay of 4 naquadah (while mostly preserving the sulfate of the sulfuric acid).

**Comment by firendlyGhost** [comment]
The dupe is most definetly not intended. its not about Nq decay
