### ISSUE TITLE
Feather Client/Forge Crash

### ISSUE THREAD

**Issue by DemonicKultimaaAlt** [GregTechCEu/GregTech#2121]
### GregTech CEu Version

v2.7.4 beta

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

All i did was open up feather client (i dont have forge cuz its blocked in my area), put in the mod, along with optifine, and loaded up 1,12. it looked alright, until it just self destructed and returned me back to the launcher screen with a crash report

### Crash Report

[latest.log](https://github.com/GregTechCEu/GregTech/files/13061004/latest.log)

**Comment by TechLord22** [comment]
We cannot explicitly support FeatherClient because it is closed source and does not state the modifications it makes to the game, however I can give you information based on what I can see in the log file.

First, it appears you are missing [CodeChickenLib](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8), which is a required dependency of GTCEu. It is required for the mod to be able to run.

If you still encounter problems after installing it, try removing Optifine. While we do try to ensure the game does not crash due to Optifine being installed, FeatherClient's modifications in combination with Optifine may be causing further issues we cannot not account for.

If all of the above does not work, then there isn't much else we can do other than to suggest using a standard launcher for modded MC such as [PrismLauncher](https://prismlauncher.org/) instead of FeatherClient. In the log file, the crash occurs within a location that appears to be added via Mixin. GTCEu and Optifine both do not use Mixins, so I must assume FeatherClient is doing so. If a standard launcher works successfully, this is likely a crash solely due to FeatherClient, and is unrelated to GTCEu.
