### ISSUE TITLE
[BUG] NuclearCraft crash with GTCEu

### ISSUE THREAD

**Issue by AffectAge** [GregTechCEu/GregTech#454]
[crash-2022-01-01_10.24.10-client.txt](https://github.com/GregTechCEu/GregTech/files/7797521/crash-2022-01-01_10.24.10-client.txt)

**Comment by pablocnvs** [comment]
That is expected as the code enabling the compatibility between those two mods hasn't been added to the release of NC:O. It is currently a PR waiting to be merged and included in a release.

**Comment by Shazuli** [comment]
You think it would be possible to create a fork of Nuclearcraft and build the project and release that build somewhere? There haven't been any commits to that repo since July. And from the look of it, the license of the project says it's fine to re-distribute as long as you don't claim it as your own.

**Comment by AffectAge** [comment]
It possible to add radion mechanic like in NuclearCraft and reactors? Maybe not so details, like in IC2. In this case NuclearCraft can be eliminated from modpack.

**Comment by ALongStringOfNumbers** [comment]
This crash should now be fixed in 2.0.3 beta
