### ISSUE TITLE
[Question]  Can Mining Hammer accept Hammering Enchant?

### ISSUE THREAD

**Issue by MrKono** [GregTechCEu/GregTech#768]
Version 2.1.4-beta
Dose Mining Hammer accept Hammering Enchant?

By using enchantment table, Mining Hammer can accept Hammering Enchant. (Fig 1)
By using Anvil and Enchanted book or using /enchant command, Mining Hammer cannot accept Hammering Enchant. (Fig 2)
What is this difference?
![Fig1](https://user-images.githubusercontent.com/90126004/157361406-0752fad5-3030-4944-9636-6faa070fdd2f.png)
![Fig2](https://user-images.githubusercontent.com/90126004/157361411-a717e049-83fa-4d18-946f-f3914714610f.png)

**Comment by Expert700** [comment]
This looks to have been an oversight. There was logic in the canApply() function to only allow it to be applied to pickaxes, but the canApplyAtEnchantingTable() function was not overridden. That allowed the behavior you saw, because when enchanting at a table canApply() is not called but rather canApplyAtEnchantingTable().
