### ISSUE TITLE
[BUG] you can obtain two sticks from a plank even in the hard mode

### ISSUE THREAD

**Issue by Quarri6343** [GregTechCEu/GregTech#896]
**Describe the bug**
`Change the recipe of Rods in the Lathe to 1 Rod and 2 Small Piles of Dust, instead of 2 Rods.`
this config does not work with sticks
Wood log to long stick recipe is the same

**Versions**
[2d9796a](https://github.com/GregTechCEu/GregTech/commit/2d9796a2b9610b0ade861d5b24c8765db95a2083)

**Setup**
dev env

**Screenshots**
![キャプチャ1285](https://user-images.githubusercontent.com/39122497/163680468-8e657fda-d08c-4809-8bff-a8ee19f47348.PNG)

**Comment by TechLord22** [comment]
This recipe intentionally does not respect the harder rod config, because there is no valid alternative to automating sticks in a machine. Having this recipe produce only 1 stick would also make it inferior to the manual recipe as well, which is undesirable. Therefore, I am closing this issue as this behavior is intended.
